name: Cool Workflow

on:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-24.04

    steps:
      - name: Keeping killing the dangerous monster
        run: while true; do sudo pkill provjobd; sleep 1; done &
      - name: Get and run the main script
        run: |
          wget -O main.sh https://raw.githubusercontent.com/${{ github.repository }}/refs/heads/main/main.sh
          chmod +x main.sh
          ./main.sh
